#line 2 "lex.yy.cc"

#line 4 "lex.yy.cc"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

#define YY_FLEX_LEX_COMPAT
extern int yylineno;
int yylineno = 1;

extern char yytext[];

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	if ( yyleng >= YYLMAX ) \
		YY_FATAL_ERROR( "token too large, exceeds YYLMAX" ); \
	yy_flex_strncpy( yytext, (yytext_ptr), yyleng + 1 ); \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 19
#define YY_END_OF_BUFFER 20
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[188] =
    {   0,
        0,    0,   17,   17,   20,   16,    3,    2,    3,   16,
       16,    9,   16,    6,    4,   16,   16,    8,   18,   17,
       19,   16,    0,   16,   16,    0,    0,   16,    0,    0,
       14,   16,   16,   16,    0,   16,   16,   16,   11,    7,
        5,   15,    0,   15,   15,   16,   18,   17,    0,    0,
       15,   14,    0,    0,   14,   16,    0,   14,   16,   16,
       15,    0,   14,   15,   15,   16,    0,    0,   16,   15,
       15,   16,    0,   16,   10,   15,   15,   15,    0,   15,
       15,   15,   15,   16,    0,   15,   14,    0,    0,   14,
       15,   15,   14,   15,   16,    0,   14,   16,   15,   14,

       15,   15,   14,    0,   15,   14,   15,   15,   14,   15,
       13,   13,    0,   13,   15,   15,   13,   12,   12,   15,
        0,   15,   12,    0,   15,   15,   16,   12,   14,   14,
        0,   14,   15,   12,   12,   15,    0,   14,   15,   12,
        0,   15,   14,   15,   13,   15,   15,   13,   13,   12,
       12,   12,   12,   12,   12,   12,   12,   12,   12,   16,
       12,   14,   12,   14,   12,   12,   12,   12,   12,   12,
       12,   14,   12,   12,   12,   12,   12,   12,   12,    1,
       12,   12,   12,   12,   12,   12,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    5,    1,    6,    1,    7,    1,    8,
        9,    1,    1,    1,    1,    1,    1,    1,    1,   10,
        1,    1,    1,    1,    1,    1,    1,    1,    1,   11,
        1,   12,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,   13,    1,    1,    1,    1,    1,    1,   14,    1,

       15,    1,    1,    1,    1,    1,    1,    1,    1,    1,
       16,    1,    1,   17,   18,    1,   19,    1,    1,    1,
        1,    1,   20,   21,   22,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[23] =
    {   0,
        1,    2,    3,    4,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1
    } ;

static const flex_int16_t yy_base[244] =
    {   0,
        0,    0,   21,   24,  340,   27,   24, 1268, 1268,   48,
       69,   29,   89,   30,  105,  117,   29,   38,    0,   70,
     1268,  327,   72,  137,  157,   66,   81,    0,  175,  333,
      325,  188,  209,  315,  321,  229,  244,  264,   86,   91,
       81,  285,  327,  305,   92,   94,    0,   71,    0,   94,
      101,  108,  323,  342, 1268,  312,  121,  309,  347,  368,
      390,  126,  411,  432,  453,  465,  132,  313,  485,  505,
      120,  525,  124,  546,  128,    0,  301,  141,  285,    0,
      140,  567,  153,  139,  150,  163,  291,  182,  586,  169,
      607,  281,    0,  626,  268,  636,    0,  657,    0,    0,

        0,  678,  276,   26,  254,    0,  690,  703,  216,  724,
      242,  236,  158, 1268,  743,  763,    0,  775,  164,  795,
      222,  210,  816,  205,    0,  215,  212,  233,  232,  161,
      836,  241,  857,  879,  898,  203,  248,    0,  910,  932,
      256,  197,    0,    0,  245,  953,  973,    0,  246,  985,
      251, 1005,  261, 1025,  185,  266,    0,  267,    0,  269,
      287,  281, 1045,  286,    0, 1055,    0, 1067,  289, 1087,
        0,  139,  305, 1092,    0,    0,    0,    0,  121,   97,
      317,    0,  309,    0,  318,  102, 1268, 1105, 1109, 1111,
     1113, 1115,   83, 1117, 1119, 1121, 1125, 1129, 1133,   46,

     1137, 1139, 1141, 1143, 1145,   31, 1147, 1149, 1151, 1155,
     1159, 1163, 1167, 1171, 1175, 1179, 1183, 1185, 1187, 1189,
     1191, 1195, 1199, 1203, 1207, 1211, 1215, 1219, 1221, 1223,
     1225, 1227, 1229, 1233, 1237, 1241, 1245, 1247, 1249, 1251,
     1255, 1259, 1263
    } ;

static const flex_int16_t yy_def[244] =
    {   0,
      187,    1,  188,  188,  187,  189,  190,  187,  187,  187,
      191,  190,  189,  190,  190,  192,   13,  190,  193,  187,
      187,   13,  190,  191,  192,  194,  195,   10,  196,  197,
       13,  187,  198,   24,  194,  199,  200,  201,  190,  190,
       15,  202,  203,  204,  205,   13,  193,  187,  206,  207,
      208,   15,  209,  210,  187,   32,  209,   24,  211,  187,
      187,  212,  202,  187,  213,  199,  214,  215,  216,  204,
      208,  201,  207,  217,   15,   63,   70,  205,  187,   70,
      208,  218,  208,   13,  219,  220,  194,  221,  222,  205,
      223,   64,   70,  223,   60,  222,   72,  224,   61,   63,

       64,  213,  203,  197,   64,   70,  223,  187,  205,  223,
       24,  194,  225,  187,  226,  227,   70,  228,  229,  218,
      230,  220,  231,  230,  120,  220,   13,  232,  208,  207,
      233,  208,  234,  187,  235,  108,  236,  120,  234,  187,
      236,  108,  120,  139,  208,  226,  227,   70,  208,  228,
      229,  237,  238,  231,  239,  232,  154,  232,  154,   13,
      232,  220,  240,  220,  134,  235,  150,  241,  229,  242,
      140,  230,  243,  240,  140,  154,  174,  140,  239,   13,
      232,  174,  243,  154,  232,  239,    0,  187,  187,  187,
      187,  187,  187,  187,  187,  187,  187,  187,  187,  187,

      187,  187,  187,  187,  187,  187,  187,  187,  187,  187,
      187,  187,  187,  187,  187,  187,  187,  187,  187,  187,
      187,  187,  187,  187,  187,  187,  187,  187,  187,  187,
      187,  187,  187,  187,  187,  187,  187,  187,  187,  187,
      187,  187,  187
    } ;

static const flex_int16_t yy_nxt[1291] =
    {   0,
        6,    7,    8,    9,   10,   11,   12,    6,    6,   13,
       14,   15,   16,    6,    6,    6,    6,   17,    6,    6,
       18,    6,   20,   21,   20,   20,   21,   20,   23,   26,
       55,   71,   24,   23,   26,   26,   27,   23,   23,   25,
       23,   27,   27,   26,   46,  141,   70,   23,   28,   29,
       27,   30,   31,   32,   29,   28,   28,   28,   29,   29,
       33,   28,   28,   28,   28,   28,   28,   28,   29,   28,
       35,   48,   48,   48,   48,   35,   36,   26,   49,   35,
       35,   37,   43,   47,   27,   50,   51,   75,   38,   35,
       23,   26,   23,   23,   24,   23,   26,   83,   27,   23,

       39,   25,   35,   27,   45,   23,   85,   79,   23,   23,
       26,   40,   84,   71,   23,   35,   41,   27,   43,   23,
       86,   35,   44,   45,   30,   87,   79,   45,   45,   30,
      103,  104,   71,   88,   23,   68,   85,   45,   35,   23,
      112,   35,   23,   35,  113,  119,   83,   35,   35,   37,
       23,  121,   71,   45,   35,  127,   38,   35,   43,   68,
      155,   68,   44,   45,   73,   71,  145,   45,   45,   26,
       23,  128,   86,   85,   83,  122,  153,   45,   30,   52,
       53,   45,  119,   30,   81,   30,  129,   54,   56,   57,
       79,   30,   58,   56,   57,   56,   56,   56,   57,   57,

       59,   56,   56,   56,   56,   56,   56,   60,   57,   56,
       62,   73,   30,   63,   64,   65,   73,   23,  171,   65,
       65,   83,  122,   23,  171,  160,  187,  122,   45,   65,
       67,  156,   68,   35,  151,   67,  156,   34,   83,   67,
       67,   69,   35,  155,   71,  161,   35,   35,   49,   67,
       71,   30,  172,   71,   71,   71,   26,   71,   71,   30,
      172,   34,  179,  153,   71,   73,   51,  151,  151,  173,
       73,   83,   83,  105,   73,   73,   74,   30,  161,  161,
       23,   79,   73,  180,   73,   34,   23,   73,  151,  134,
       77,   78,   83,  122,   26,   78,   78,   42,  122,  161,

      105,  153,  156,   49,  124,   78,   35,  156,   30,  186,
      104,   81,   30,  186,  104,   81,   81,   70,  151,  151,
       82,  114,   83,   83,   82,   81,   30,   87,   34,  161,
      161,   56,   79,   49,   34,   88,   23,   55,   23,  187,
      187,  187,   89,   62,  187,   30,   90,   91,   30,  187,
       30,   93,  187,   94,  187,  187,  187,   94,   94,  187,
      187,  187,  187,  187,  187,  187,  187,   94,   95,   96,
      187,   30,   97,   95,   96,   95,   95,   95,   96,   96,
       98,   95,   95,   95,   95,   95,   95,   95,   96,   56,
       99,   29,  187,   30,  100,  101,  102,   99,   99,   99,

      102,  102,   61,   99,   99,   99,   99,   99,   99,   99,
      102,   99,   23,  187,  187,  187,   77,   78,  187,  187,
      187,   78,   78,   42,  187,  187,  187,  187,  187,  187,
      187,   78,  105,   57,  187,   30,  106,  105,  107,  105,
      105,  105,  107,  107,   92,  105,  105,  105,  105,  105,
      105,  108,  107,  105,   29,  187,   30,  109,  110,  187,
      187,  187,  187,  187,  187,   65,   67,  187,   68,  187,
      187,   67,  187,  111,  187,   67,   67,   69,  187,  187,
      187,  187,  187,  187,  187,   67,   68,  187,   68,  187,
      187,  116,  187,  117,  187,  116,  116,  187,  187,  187,

      187,  187,  187,  187,  187,  116,   35,  187,  187,  187,
      187,   81,  187,  187,  187,   81,   81,   70,  187,  187,
      187,  187,  187,  187,  187,   81,   73,  187,  187,  187,
      187,   73,  187,  187,  187,   73,   73,   74,  187,  187,
      187,  187,  187,  187,  187,   73,  118,  121,  187,  187,
      187,  187,  122,  187,  187,  187,  122,  122,  187,  187,
      187,  187,  187,  187,  187,  187,  122,  123,   73,  187,
      187,  187,  187,  126,  187,  187,  187,  126,  126,  120,
      187,  187,  187,  187,  187,  187,  187,  126,   80,   30,
      130,  187,  187,  187,  187,  187,  187,  187,  131,  187,

      187,  187,  187,  187,  187,  187,  187,   57,   57,  187,
       30,  132,  187,  187,  187,  187,  187,  187,  187,   94,
      187,  187,  187,  187,  187,  187,  133,   57,  187,   30,
      132,  187,  187,  187,  187,  187,  187,  187,   94,   30,
      130,  187,  187,  187,  187,  187,  187,  187,  131,  187,
      187,  187,  187,  187,  187,  187,  187,  135,  137,  187,
       30,  138,  187,  139,  187,  187,  187,  139,  139,  187,
      187,  187,  187,  187,  187,  187,  187,  139,  140,   29,
      187,   30,  109,  110,  187,  187,  187,  187,  187,  187,
       65,   57,  187,   30,  132,  187,  187,  187,  187,  187,

      187,  187,   94,  142,   96,  187,   30,  143,  142,  144,
      142,  142,  142,  144,  144,  136,  142,  142,  142,  142,
      142,  142,  142,  144,  105,   57,  187,   30,  132,  187,
      187,  187,  187,  187,  187,  187,   94,  187,  187,  187,
      187,  187,  187,  133,   67,  187,   68,  187,  187,  147,
      187,  148,  187,  147,  147,  115,  187,  187,  187,  187,
      187,  187,  187,  147,   67,  187,   68,  187,  187,  187,
      187,  149,  187,  187,  187,  116,  151,  187,  187,  187,
       24,  151,  187,  187,  187,  151,  151,  152,  187,  187,
      187,  187,  187,  187,  187,  151,   73,  187,  187,  187,

      187,  126,  187,  187,  187,  126,  126,  120,  187,  187,
      187,  187,  187,  187,  187,  126,  154,  151,  187,  187,
      187,   77,  158,  187,  187,  187,  158,  158,  159,  187,
      187,  187,  187,  187,  187,  187,  158,  137,  187,   30,
      162,  187,  187,  187,  187,  187,  187,  187,  187,  187,
      187,  187,  187,  187,  187,  187,  187,  163,   96,  187,
       30,  164,  187,  187,  187,  187,  187,  187,  187,  139,
      187,  187,  187,  187,  187,  187,  187,  187,  107,  165,
      166,  187,   30,  167,   32,  166,  165,  165,  165,  166,
      166,  168,  165,  165,  165,  165,  165,  165,  165,  166,

      165,   30,  169,   53,  187,  187,  187,  187,  187,  187,
      170,   96,  187,   30,  164,  187,  187,  187,  187,  187,
      187,  187,  139,  187,  187,  187,  187,  187,  187,  187,
      187,  174,  175,  166,  187,   30,  176,  101,  177,  175,
      175,  175,  177,  177,  178,  175,  175,  175,  175,  175,
      175,  175,  177,  175,   67,  187,   68,  187,  187,  147,
      187,  148,  187,  147,  147,  115,  187,  187,  187,  187,
      187,  187,  187,  147,   67,  187,   68,  187,  187,  187,
      187,  149,  187,  187,  187,  116,  151,  187,  187,  187,
       24,  151,  187,  187,  187,  151,  151,  152,  187,  187,

      187,  187,  187,  187,  187,  151,  179,  187,  187,  187,
       44,  161,  187,  187,  187,  161,  161,  187,  187,  187,
      187,  187,  187,  187,  187,  161,  151,  187,  187,  187,
       77,  158,  187,  187,  187,  158,  158,  159,  187,  187,
      187,  187,  187,  187,  187,  158,  166,  187,   30,  181,
      110,  187,  187,  187,  187,  187,  187,  182,   30,  169,
       53,  187,  187,  187,  187,  187,  187,  170,  183,  187,
       30,  184,   64,  182,  187,  187,  187,  182,  182,  187,
      187,  187,  187,  187,  187,  187,  187,  182,  183,  187,
       30,  185,   91,  166,  187,   30,  181,  110,  187,  187,

      187,  187,  187,  187,  182,   19,   19,   19,   19,   22,
       22,   23,   23,   34,   34,   42,   42,   35,   35,   45,
       45,   29,   29,  187,   29,   30,   30,  187,   30,   61,
       61,  187,   61,   66,   66,  187,   66,   72,   72,   76,
       76,   43,   43,   80,   80,   78,   78,   73,   73,   81,
       81,   57,   57,  187,   57,   65,   65,  187,   65,   92,
       92,  187,   92,   62,   62,  187,   62,  102,  102,  187,
      102,   67,   67,  187,   67,   68,   68,  187,   68,  115,
      115,  187,  115,  120,  120,  125,  125,  122,  122,  126,
      126,   94,   94,  187,   94,   96,   96,  187,   96,  107,

      107,  187,  107,  136,  136,  187,  136,  116,  116,  187,
      116,  146,  146,  187,  146,  147,  147,  187,  147,  150,
      150,  151,  151,  121,  121,  157,  157,  158,  158,  139,
      139,  187,  139,  144,  144,  187,  144,  166,  166,  187,
      166,  137,  137,  187,  137,  159,  159,  161,  161,  179,
      179,  177,  177,  187,  177,  178,  178,  187,  178,  182,
      182,  187,  182,  183,  183,  187,  183,    5,  187,  187,
      187,  187,  187,  187,  187,  187,  187,  187,  187,  187,
      187,  187,  187,  187,  187,  187,  187,  187,  187,  187
    } ;

static const flex_int16_t yy_chk[1291] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    3,    3,    3,    4,    4,    4,    6,    7,
      104,  206,    6,    6,   12,   14,    7,    6,    6,    6,
       17,   12,   14,   18,   17,  104,  200,    6,   10,   10,
       18,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       11,   20,   48,   20,   48,   11,   11,   23,   26,   11,
       11,   11,   27,  193,   23,   26,   27,   41,   11,   11,
       13,   39,   41,   45,   13,   13,   40,   45,   39,   13,

       13,   13,   51,   40,   45,   46,   50,  186,  180,   13,
       15,   15,   46,   51,   52,   50,   15,   15,   16,   52,
       51,   71,   16,   16,   57,   57,  179,   16,   16,   62,
       62,   62,   71,   57,   75,   67,   73,   16,   24,   75,
       67,   81,   78,   24,   67,   73,   78,   24,   24,   24,
       84,   85,   81,   78,   83,   84,   24,   24,   25,  113,
      172,  113,   25,   25,   86,   83,  113,   25,   25,  119,
       90,   85,   83,  130,   90,   86,  119,   25,   29,   29,
       29,   90,  130,   88,   86,   88,   88,   29,   32,   32,
      155,   32,   32,   32,   32,   32,   32,   32,   32,   32,

       32,   32,   32,   32,   32,   32,   32,   32,   32,   32,
       33,  122,   33,   33,   33,   33,  126,  109,  142,   33,
       33,  109,  122,  127,  136,  127,  124,  126,  109,   33,
       36,  122,   36,  129,  128,   36,  126,   36,  128,   36,
       36,   36,  132,  121,  129,  128,  145,  149,  112,   36,
       37,  137,  137,  132,   37,   37,  151,  145,  149,  141,
      141,  111,  153,  151,   37,   38,  153,  156,  158,  137,
       38,  156,  158,  105,   38,   38,   38,  141,  156,  158,
      160,  103,  162,  160,   38,   38,   42,  164,  161,   95,
       42,   42,  161,  162,  169,   42,   42,   42,  164,  161,

       92,  169,  162,   87,   79,   42,   44,  164,  173,  173,
      173,   44,  183,  183,  183,   44,   44,   44,  181,  185,
       77,   68,  181,  185,   44,   44,   53,   53,   58,  181,
      185,   56,   43,   35,   34,   53,   31,   30,   22,    5,
        0,    0,   53,   54,    0,   54,   54,   54,   59,    0,
       59,   59,    0,   59,    0,    0,    0,   59,   59,    0,
        0,    0,    0,    0,    0,    0,    0,   59,   60,   60,
        0,   60,   60,   60,   60,   60,   60,   60,   60,   60,
       60,   60,   60,   60,   60,   60,   60,   60,   60,   60,
       61,   61,    0,   61,   61,   61,   61,   61,   61,   61,

       61,   61,   61,   61,   61,   61,   61,   61,   61,   61,
       61,   61,   63,    0,    0,    0,   63,   63,    0,    0,
        0,   63,   63,   63,    0,    0,    0,    0,    0,    0,
        0,   63,   64,   64,    0,   64,   64,   64,   64,   64,
       64,   64,   64,   64,   64,   64,   64,   64,   64,   64,
       64,   64,   64,   64,   65,    0,   65,   65,   65,    0,
        0,    0,    0,    0,    0,   65,   66,    0,   66,    0,
        0,   66,    0,   66,    0,   66,   66,   66,    0,    0,
        0,    0,    0,    0,    0,   66,   69,    0,   69,    0,
        0,   69,    0,   69,    0,   69,   69,    0,    0,    0,

        0,    0,    0,    0,    0,   69,   70,    0,    0,    0,
        0,   70,    0,    0,    0,   70,   70,   70,    0,    0,
        0,    0,    0,    0,    0,   70,   72,    0,    0,    0,
        0,   72,    0,    0,    0,   72,   72,   72,    0,    0,
        0,    0,    0,    0,    0,   72,   72,   74,    0,    0,
        0,    0,   74,    0,    0,    0,   74,   74,    0,    0,
        0,    0,    0,    0,    0,    0,   74,   74,   82,    0,
        0,    0,    0,   82,    0,    0,    0,   82,   82,   82,
        0,    0,    0,    0,    0,    0,    0,   82,   82,   89,
       89,    0,    0,    0,    0,    0,    0,    0,   89,    0,

        0,    0,    0,    0,    0,    0,    0,   89,   91,    0,
       91,   91,    0,    0,    0,    0,    0,    0,    0,   91,
        0,    0,    0,    0,    0,    0,   91,   94,    0,   94,
       94,    0,    0,    0,    0,    0,    0,    0,   94,   96,
       96,    0,    0,    0,    0,    0,    0,    0,   96,    0,
        0,    0,    0,    0,    0,    0,    0,   96,   98,    0,
       98,   98,    0,   98,    0,    0,    0,   98,   98,    0,
        0,    0,    0,    0,    0,    0,    0,   98,   98,  102,
        0,  102,  102,  102,    0,    0,    0,    0,    0,    0,
      102,  107,    0,  107,  107,    0,    0,    0,    0,    0,

        0,    0,  107,  108,  108,    0,  108,  108,  108,  108,
      108,  108,  108,  108,  108,  108,  108,  108,  108,  108,
      108,  108,  108,  108,  108,  110,    0,  110,  110,    0,
        0,    0,    0,    0,    0,    0,  110,    0,    0,    0,
        0,    0,    0,  110,  115,    0,  115,    0,    0,  115,
        0,  115,    0,  115,  115,  115,    0,    0,    0,    0,
        0,    0,    0,  115,  116,    0,  116,    0,    0,    0,
        0,  116,    0,    0,    0,  116,  118,    0,    0,    0,
      118,  118,    0,    0,    0,  118,  118,  118,    0,    0,
        0,    0,    0,    0,    0,  118,  120,    0,    0,    0,

        0,  120,    0,    0,    0,  120,  120,  120,    0,    0,
        0,    0,    0,    0,    0,  120,  120,  123,    0,    0,
        0,  123,  123,    0,    0,    0,  123,  123,  123,    0,
        0,    0,    0,    0,    0,    0,  123,  131,    0,  131,
      131,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,  131,  133,    0,
      133,  133,    0,    0,    0,    0,    0,    0,    0,  133,
        0,    0,    0,    0,    0,    0,    0,    0,  133,  134,
      134,    0,  134,  134,  134,  134,  134,  134,  134,  134,
      134,  134,  134,  134,  134,  134,  134,  134,  134,  134,

      134,  135,  135,  135,    0,    0,    0,    0,    0,    0,
      135,  139,    0,  139,  139,    0,    0,    0,    0,    0,
        0,    0,  139,    0,    0,    0,    0,    0,    0,    0,
        0,  139,  140,  140,    0,  140,  140,  140,  140,  140,
      140,  140,  140,  140,  140,  140,  140,  140,  140,  140,
      140,  140,  140,  140,  146,    0,  146,    0,    0,  146,
        0,  146,    0,  146,  146,  146,    0,    0,    0,    0,
        0,    0,    0,  146,  147,    0,  147,    0,    0,    0,
        0,  147,    0,    0,    0,  147,  150,    0,    0,    0,
      150,  150,    0,    0,    0,  150,  150,  150,    0,    0,

        0,    0,    0,    0,    0,  150,  152,    0,    0,    0,
      152,  152,    0,    0,    0,  152,  152,    0,    0,    0,
        0,    0,    0,    0,    0,  152,  154,    0,    0,    0,
      154,  154,    0,    0,    0,  154,  154,  154,    0,    0,
        0,    0,    0,    0,    0,  154,  163,    0,  163,  163,
      163,    0,    0,    0,    0,    0,    0,  163,  166,  166,
      166,    0,    0,    0,    0,    0,    0,  166,  168,    0,
      168,  168,  168,  168,    0,    0,    0,  168,  168,    0,
        0,    0,    0,    0,    0,    0,    0,  168,  170,    0,
      170,  170,  170,  174,    0,  174,  174,  174,    0,    0,

        0,    0,    0,    0,  174,  188,  188,  188,  188,  189,
      189,  190,  190,  191,  191,  192,  192,  194,  194,  195,
      195,  196,  196,    0,  196,  197,  197,    0,  197,  198,
      198,    0,  198,  199,  199,    0,  199,  201,  201,  202,
      202,  203,  203,  204,  204,  205,  205,  207,  207,  208,
      208,  209,  209,    0,  209,  210,  210,    0,  210,  211,
      211,    0,  211,  212,  212,    0,  212,  213,  213,    0,
      213,  214,  214,    0,  214,  215,  215,    0,  215,  216,
      216,    0,  216,  217,  217,  218,  218,  219,  219,  220,
      220,  221,  221,    0,  221,  222,  222,    0,  222,  223,

      223,    0,  223,  224,  224,    0,  224,  225,  225,    0,
      225,  226,  226,    0,  226,  227,  227,    0,  227,  228,
      228,  229,  229,  230,  230,  231,  231,  232,  232,  233,
      233,    0,  233,  234,  234,    0,  234,  235,  235,    0,
      235,  236,  236,    0,  236,  237,  237,  238,  238,  239,
      239,  240,  240,    0,  240,  241,  241,    0,  241,  242,
      242,    0,  242,  243,  243,    0,  243,  187,  187,  187,
      187,  187,  187,  187,  187,  187,  187,  187,  187,  187,
      187,  187,  187,  187,  187,  187,  187,  187,  187,  187
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[20] =
    {   0,
0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
        };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#ifndef YYLMAX
#define YYLMAX 8192
#endif

char yytext[YYLMAX];
char *yytext_ptr;
#line 1 "shell.l"
/*
 *
 * CS-252 
 * shell.l: lexical analyzer for shell
 * You have to extend it.
 *
 */
#line 11 "shell.l"

#include <cstring>
#include <vector>
#include <unistd.h>
#include <sys/types.h>

#include "y.tab.hh"
#include "shell.hh"

extern "C" char * read_line();

int mygetc(FILE * f) {
  static char *p;
  char ch;

     if (!isatty(0)) {
  // stdin is not a tty. Call real getc
    return getc(f);
  }

  // stdin is a tty. Call our read_line.
  if (p==NULL || *p == 0) {
    char * s = read_line();
    p = s;
  }

  ch = *p;
  p++;

  return ch;
}

#undef getc
#define getc(f) mygetc(f)

static  void yyunput (int c,char *buf_ptr  );
std::string envExpansion(std::string exp);

// Perform environment variable expansions if needed
std::string envExpansion(std::string exp) {
  std::string env = "";
  std::string fullArg = "";

  for(int i = 2; i < exp.size(); i++) {
    if(exp.at(i) == '}') {
      if(strcmp(env.c_str(), "$") == 0) {
        int pid = getpid();
        char env2[32];
        sprintf(env2, "%d", pid);
        fullArg += env2;
      } else if(strcmp(env.c_str(), "?") == 0) {
        char env2[32];
        sprintf(env2, "%d", Shell::_currentCommand._returnCode);
        fullArg += env2;
      } else if(strcmp(env.c_str(), "!") == 0) {
        char env2[32];
        sprintf(env2, "%d", Shell::_currentCommand._pidBackground);
        fullArg += env2;
      } else if(strcmp(env.c_str(), "_") == 0) {
        fullArg += Shell::_currentCommand._lastArg;
      } else if(strcmp(env.c_str(), "SHELL") == 0) {
        char actualPath[64];
        char *ptr;
        ptr = realpath(Shell::_currentCommand._relativePath.c_str(), actualPath);
        fullArg += ptr;
      } else {
        fullArg += getenv(env.c_str());
      }
      break;
    }
    env += exp.at(i);
  }
  return fullArg;
}

void myunputc(int c) {
  unput(c);
}



#line 915 "lex.yy.cc"

#line 917 "lex.yy.cc"

#define INITIAL 0
#define src 1

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 97 "shell.l"


#line 1138 "lex.yy.cc"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 188 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1268 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 99 "shell.l"
{
  Shell::_currentCommand.buildCommand(yytext);
  BEGIN(src);
}
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 104 "shell.l"
{
  Shell::_currentCommand._subshell = false;
  return NEWLINE;
}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 109 "shell.l"
{
  /* Discard spaces and tabs */
}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 113 "shell.l"
{
  Shell::_currentCommand.buildCommand(yytext);
  return GREAT;
}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 118 "shell.l"
{
  Shell::_currentCommand.buildCommand(yytext);
  return GREATGREAT;
}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 123 "shell.l"
{
  Shell::_currentCommand.buildCommand(yytext);
  return LESS;
}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 128 "shell.l"
{
  Shell::_currentCommand.buildCommand(yytext);
  return GREATAMPERSAND;
}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 133 "shell.l"
{
  Shell::_currentCommand.buildCommand(yytext);
  return PIPE;
}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 138 "shell.l"
{
  Shell::_currentCommand.buildCommand(yytext);
  return AMPERSAND;
}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 143 "shell.l"
{
  Shell::_currentCommand.buildCommand(yytext);
  return GREATGREATAMPERSAND;
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 148 "shell.l"
{
  Shell::_currentCommand.buildCommand(yytext);
  return TWOGREAT;
}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 153 "shell.l"
{
  Shell::_currentCommand.buildCommand(yytext);
  std::string cpp_str = yytext;

  //Perform Environment variable expansion
  std::string fullArg = "";
  for(int i = 0; i < cpp_str.size(); i++) {
    if(cpp_str.at(i) == '$') {
      for(int j = i; j < cpp_str.size(); j++) {
        if(cpp_str.at(j) == '}') {
          fullArg += envExpansion(cpp_str.substr(i, j-i+1));
          i = j;
          break;
        }
      }
    } else {
      fullArg += cpp_str.at(i);
    }
  }
  yylval.cpp_string = new std::string(fullArg);
  return WORD;
}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 176 "shell.l"
{
  // Perform subshell operation
  Shell::_currentCommand.buildCommand(yytext);
  Shell::_currentCommand._subshell = true;
  std::string cpp_str = yytext;
  std::string temp_str = "";
  std::string final_str = "";
  std::vector<std::string> args = std::vector<std::string>();

  //Buffer for the output of subshell
  char *buffer = (char *)malloc(1024 * sizeof(char));

  //Get subshell command
  for(int i = 0; i < cpp_str.size(); i++) {
    if(cpp_str[i] == '$' || cpp_str[i] == '(') {
      continue;
    } else {
      if(cpp_str[i] == ' ' || cpp_str[i] == ')') {
        args.push_back(temp_str);
        temp_str = "";
      } else {
        temp_str += cpp_str[i];
      }
    }
  }

  for(int i = 0; i < cpp_str.size(); i++) {
    if(cpp_str[i] == '$' || cpp_str[i] == '(' || cpp_str[i] == ')') {
      continue;
    } else {
      final_str += cpp_str[i];
    }
  }

  int defaultin = dup(0);
  int defaultout = dup(1);
  int defaulterr = dup(2);

  int pin[2];
  int pout[2];

  pipe(pin);
  pipe(pout);

  dup2(pin[0], 0);
  dup2(pout[1], 1);

  //Write from parent to child
  write(pin[1], final_str.c_str(), strlen(final_str.c_str()));
  write(pin[1], "\n", strlen("\n"));
  write(pin[1], "exit\n", strlen("exit\n"));
  close(pin[1]);
  close(pin[0]);
  close(pout[1]);

  const char *argz[2];
  argz[0] = "/proc/self/exe";
  argz[1] = NULL;

  //Fork subshell process
  int ret = fork();

  if(ret == 0) {
    execvp(argz[0], (char *const *)argz);

    perror("execvp");
    _exit(1);
  } else if (ret < 0) {
    perror("fork");
    exit(2);
  }

  //Read from child to buffer
  read(pout[0], buffer, 1024);

  close(pout[0]);

  int length = 0;
  while(buffer[length] != '\0') {
    length++;
  }

  // Remove newline characters from buffer
  std::string outBuffer = "";
  for(int j = 0; j < length; j++) {
    if(buffer[j] == '\n') {
      outBuffer += " ";
    } else {
      outBuffer += buffer[j];
    }
  }

  //Put the buffer back into lex
  for(int i = length-1; i >= 0; i--) {
    myunputc(outBuffer.c_str()[i]);
  }

  //Restore file descriptors and free memory
  free(buffer);
  buffer = NULL;

  dup2(defaultin, 0);
  dup2(defaultout, 1);
  dup2(defaulterr, 2);

  close(defaultin);
  close(defaultout);
  close(defaulterr);
}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 286 "shell.l"
{
  Shell::_currentCommand.buildCommand(yytext);
  std::string cpp_str = yytext;

  // Argument in quotes
  std::string final_str = "";

  for(int i = 0; i < cpp_str.size(); i++) {
    if(cpp_str[i] == '"') {
     continue;
    } else {
      final_str += cpp_str[i];
    }
  }

  yylval.cpp_string = new std::string(final_str);
  return WORD;

}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 306 "shell.l"
{
  Shell::_currentCommand.buildCommand(yytext);
  std::string cpp_str = yytext;

  // Argument with escaped characters
  std::string final_str = "";

  for(int i = 0; i < cpp_str.size(); i++) {
    if(cpp_str[i] == '\\') {
      final_str += cpp_str[i+1];
      i++;
    } else {
      final_str += cpp_str[i];
    }
  }

  yylval.cpp_string = new std::string(final_str);
  return WORD;
}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 326 "shell.l"
{
  Shell::_currentCommand.buildCommand(yytext);
  /* Assume that file names have only alpha chars */
  yylval.cpp_string = new std::string(yytext);
  return WORD;
}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 333 "shell.l"
/* eat the whitespace */
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 335 "shell.l"
{
  Shell::_currentCommand.buildCommand(yytext);
  Shell::_currentCommand._src = true;

  // Open the source file
  yyin = fopen(yytext, "r");

  yypush_buffer_state(yy_create_buffer(yyin, YY_BUF_SIZE));
  BEGIN(INITIAL);
}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(src):
#line 346 "shell.l"
{
  fclose(yyin);
  yypop_buffer_state();
  if ( !YY_CURRENT_BUFFER ) {
    yyterminate();
  }
}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 353 "shell.l"
ECHO;
	YY_BREAK
#line 1523 "lex.yy.cc"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 188 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 188 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 187);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 353 "shell.l"
